### ISSUE TITLE
GitHash on generated selectorsyncset always one commit behind

### ISSUE THREAD

**Issue by rafael-azevedo** [openshift/managed-cluster-config#20]
Since the selectorsyncset template in /hash is always committed it will always have a githash that points to the previous commit.

**Comment by jewzaam** [comment]
Fixed by using IMAGE_TAG parameter in the Template.

https://github.com/openshift/managed-cluster-config/blob/master/scripts/templates/selectorsyncset.yaml#L5

https://github.com/openshift/managed-cluster-config/blob/master/hack/00-osd-managed-cluster-config.selectorsyncset.yaml.tmpl#L20
