### ISSUE TITLE
Makefile failing in CI workflow (release/prow)

### ISSUE THREAD

**Issue by rogbas** [openshift/managed-cluster-config#59]
A Dockerfile has been created to integrate this repo to the `openshift/release` process, so every time a PR is created, `make` will be executed inside a container, generating the assets and validating the process.

There seems to be a problem that only manifests in the CI platform, causing the following command to fail, apparently because git config does not return the expected result:

`basename $$((git config --get-regex remote\.*\.url 2>/dev/null | cut -d ' ' -f2 || pwd) | head -n1 | sed 's|.git||g')`

https://github.com/openshift/managed-cluster-config/blob/master/project.mk

Building the image locally with docker or imagebuilder (same tool used by ci-operator) works fine.

The failed CI job: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/4323/rehearse-4323-pull-ci-openshift-managed-cluster-config-master-images/9

@ALimaRedHat

**Comment by rogbas** [comment]
If we can't map why this issue is happening in CI, a possible workaround would be not setting the folder name dynamically in https://github.com/openshift/managed-cluster-config/blob/master/project.mk based on git config output.

**Comment by cblecker** [comment]
I just verified that prow's podutils doesn't actually provide a proper git remote, so anything that relies on that will fail.

You could perhaps not do it dynamically, or you could (in CI) consume some of the job env vars provided: https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#job-environment-variables

**Comment by ALimaRedHat** [comment]
ping @jewzaam

**Comment by jewzaam** [comment]
Easy to reproduce:

```
cd `mktemp -d`
basename $((git config --get-regex remote\.*\.url 2>/dev/null | cut -d ' ' -f2 || pwd) | head -n1 | sed 's|.git||g')
basename: missing operand
Try 'basename --help' for more information.
```
We can have it fallback on the env var `REPO_NAME` with this:
```
basename $((git config --get-regex remote\.*\.url 2>/dev/null | cut -d ' ' -f2 || pwd) | head -n1 | sed 's|.git||g') 2>/dev/null || echo $REPO_NAME
```

In project.mk would be:
```
REPO_NAME?=$(shell basename $$((git config --get-regex remote\.*\.url 2>/dev/null | cut -d ' ' -f2 || pwd) | head -n1 | sed 's|.git||g') 2>/dev/null || echo $$REPO_NAME)
```

**Comment by cblecker** [comment]
Hmm.. so the makefile is using the ?= operand.. then it should pick up the variable from CI anyways and not try to set it.

**Comment by cblecker** [comment]
Actually, I lied.. the ci-operator itself has this var, but the build won't by default

**Comment by cblecker** [comment]
So the build itself is a OpenShift build, so it happens in a different environment than the ci-operator or the prowjob. We may need another way do this, or just hard code the variable somewhere.

**Comment by jewzaam** [comment]
We didn't want to hard code this because it's copied between repos.  But, we could move this out of standard.mk and put it in project.mk and hard code to the name of the repo.

**Comment by cblecker** [comment]
It's already in project.mk:
https://github.com/openshift/managed-cluster-config/blob/761476bccc9e797f9cf2f011f7926f33dc70be64/project.mk#L7

I'm confused.. am I missing something?

**Comment by ALimaRedHat** [comment]
I made a PR for this issue - #61
